Elemental validation and improvements when using SL Micro 6.0
suse-edge/edge-image-builder pull request #549
Opened 2024-08-28 03:11 UTC by dbw7

This PR changes the way Elemental is handled depending on the API Version of the image definition. The reason being: 1.1 only supports SL Micro 6.0 and 1.0 only supports 5.5 so we can operate under that assumption when working with Elemental.

What happens now is that when using 1.0, the Elemental handling is the same and it uses the repositories found in `artifacts.yaml`, however, when using 1.1, those repositories are no longer used and instead the necessary Elemental packages are found through RPM resolution inside of the SL Micro 6.0 image. This now means that when using Elemental with 6.0, you need to specify a package registration code.

Additionally, to supplement this, I added validation for the Elemental configuration directory and for the registration code.

2024-08-28 04:55 UTC, atanasdinov requested changes
Discussed offline - only putting out the conclusions for visibility.

1. Switching up Elemental source requires a change to `artifacts.yaml` which also means some of the code here could (or would) be removed
2. Elemental RPMs shipped with SL Micro 6.0 are not latest yet and we're unable to rely on them at this point in time
3. Validating empty directories should be part of https://github.com/suse-edge/edge-image-builder/issues/276

2024-09-09 15:30 UTC, jdob commented
Quick update: The proper RPMs are now available in the SL Micro 6.0 repo, so concern #2 from Atanas' comment is addressed.

2024-09-19 09:16 UTC, atanasdinov reviewed
I feel like this must land at this point... There's still no response from the ECM team.

2024-09-19 09:16 UTC, atanasdinov commented on pkg/eib/eib.go
> +	if ctx.ImageDefinition.APIVersion == "1.0" {
This isn't a good indicator. You can build SL Micro 6.0 images with both API versions 1.0 and 1.1. Do we bite the bullet and only allow Elemental builds for 6.0 in EIB v1.1?

2024-09-20 17:24 UTC, atanasdinov commented on pkg/image/validation/elemental_test.go
> +		`valid 1.1`: {
What does 1.1 indicate here?

2024-09-20 17:24 UTC, atanasdinov commented on pkg/image/validation/elemental_test.go
> +		`1.1 no registration code`: {
Same?

2024-09-20 17:38 UTC, atanasdinov commented on pkg/image/validation/elemental_test.go
> +func TestValidateElementalConfigDir(t *testing.T) {
I'd suggest to split this up. It's unreadable at this point and this is not what table tests are suited for.

2024-09-24 07:38 UTC, atanasdinov commented on pkg/image/validation/elemental.go
> +		failures = append(failures, FailedValidation{
We need to return after this. No point in trying to make assertions on what's in the directory if we're unable to read it.

2024-09-24 07:38 UTC, atanasdinov commented on pkg/image/validation/elemental_test.go
> +	}
We don't need all of this for single value assertion.

2024-09-24 07:38 UTC, atanasdinov commented on pkg/image/validation/elemental_test.go
> +	}
Same.

2024-09-24 07:38 UTC, atanasdinov commented
Please drop the unused properties from `artifacts.yaml`.

2024-09-24 14:45 UTC, atanasdinov commented on RELEASE_NOTES.md
> +* Improved Elemental handling when using SL Micro 6.0
Can we rephrase this and move it to the API section below? `Elemental configuration now requires a registration code in order to install the necessary RPMs from the official sources` or something similar.

2024-09-24 14:59 UTC, atanasdinov approved these changes

2024-09-24 15:07 UTC, merged